{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jewelry-shop.fullname" . }}-pvc
  labels:
    {{- include "jewelry-shop.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass | default "nfs" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
